### ISSUE TITLE
Permissions

### ISSUE THREAD

**Issue by tayduds07** [spencermountain/wikipedia-to-mongodb#11]
![git](https://cloud.githubusercontent.com/assets/15025380/23642456/17a537b8-02b8-11e7-9feb-e7de87097ac9.PNG)

Every time i run git clone git@github.com:spencermountain/wikipedia-to-mongodb.git.. I get the permission error.. I've disabled selinux and turned off firewalls.. 
I'm not sure what im doing wrong.

**Comment by spencermountain** [comment]
hey, the github ssh permissions are [weird](https://help.github.com/articles/connecting-to-github-with-ssh/), i recommend using the http endpoint
```bash
git clone https://github.com/spencermountain/wikipedia-to-mongodb.git
```
cheers
