### ISSUE TITLE
npm install

### ISSUE THREAD

**Issue by tayduds07** [spencermountain/wikipedia-to-mongodb#12]
![databases-2017-03-07-14-45-16](https://cloud.githubusercontent.com/assets/15025380/23679445/371a9d26-0345-11e7-9834-4c8954417488.png)
When trying to run npm install I get errors

**Comment by spencermountain** [comment]
hi, seems like an issue installing `iconv`. it is required by `xml-stream`. 
that's the best I can do!
cheers

**Comment by tayduds07** [comment]
Got it to work! Thank you!
