### ISSUE TITLE
fatal error js stack trace

### ISSUE THREAD

**Issue by LudvigOlsen** [spencermountain/wikipedia-to-mongodb#13]
After reaching "Disruptor Beam 9192071"  I get this message. I have 32gb RAM. Is it a special finishing up process that failed or just that article?
Should I do something or have all the articles been moved to mongodb? :)

Thanks!

> 
> <--- Last few GCs --->
> 
> 51669740 ms: Scavenge 1394.1 (1457.7) -> 1394.1 (1457.7) MB, 0.2 / 0 ms (+ 2.4 ms in 2 steps since last GC) [allocation failure] [incremental marking delaying mark-sweep].
> 51670266 ms: Mark-sweep 1394.1 (1457.7) -> 1284.9 (1457.7) MB, 525.2 / 0 ms (+ 3.5 ms in 4 steps since start of marking, biggest step 2.2 ms) [last resort gc].
> 51670912 ms: Mark-sweep 1284.9 (1457.7) -> 1284.9 (1457.7) MB, 646.1 / 0 ms [last resort gc].
> 
> 
> <--- JS stacktrace --->
> 
> ==== JS stack trace =========================================
> 
> Security context: 0x3872217b4629 <JS Object>
>     1: RegExpExecNoTests [native regexp.js:~59] [pc=0x11185f437ec3] (this=0x3872217d8991 <JS Global Object>,j=0x2f5829f089b9 <JS RegExp>,k=0x2f5829f08991 <String[104]: Disruptor Beam is a developer of mobile and social game products based in [[Framingham, Massachusetts]].>,n=0)
>     2: match(aka match) [native string.js:~118] [pc=0x11185f437ce3] (this=0x2f5829f08991 <String[104]: Disruptor Beam ...
> 
> FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - process out of memory
> Aborted
>

**Comment by spencermountain** [comment]
hi Ludvig, yikes. I'm not sure what happened.
you can always check how many articles it imported with `db.wikipedia.count()` or something similar, in the mongo shell.
yeah, it's been a long time since i looked at this repo. 
You could skip that particular page by putting a return [somewhere in here](https://github.com/spencermountain/wikipedia-to-mongodb/blob/master/index.js#L50) and that may help.
if you find something helpful, please make a pull-request!
cheers

**Comment by spencermountain** [comment]
did you use the `--worker` flag?

**Comment by LudvigOlsen** [comment]
Hi Spencer,
It seems to have transferred 9191623 articles, which should be enough by far :)
Thanks for your reply :) I'm not a js man, so it would take too much time for me to fix whatever error that was. Thanks for the script, btw.

And no, I didn't use the worker flag. Probably should have. ;)
