### ISSUE TITLE
Getting error using Workers

### ISSUE THREAD

**Issue by trickidicki** [spencermountain/wikipedia-to-mongodb#14]
On Windows x64, using the -w option I get errors from the file stream/BZip stream. Adding an error handler 
`  var stream = fs.createReadStream(file, {bufferSize: 64 * 1024}).pipe(bz2());
  stream.on('error', function(err){console.log("unbzip2-stream error: " + err); process.exit(1)})
  var xml = new XmlStream(stream);`

I get 

> rangeerror: Array buffer allocation failed

Works fine (but much more slowly) using single-threaded.

Any ideas?

**Comment by spencermountain** [comment]
hi trickidicki, sorry I don't. best to ask the [XmlStream](https://github.com/assistunion/xml-stream) project. let me know if it's a config thing or something, i'm happy to change how it's called.
cheers
