### ISSUE TITLE
Continue importing without start from the beginning

### ISSUE THREAD

**Issue by imoonkey** [spencermountain/wikipedia-to-mongodb#2]
Hi. I have been importing the english wikipedia articles (53GB) into my mongodb database for more than a day. And my computer got very slow, and I have to reboot it as it does not respond to any input. 

But the importing was not done, and I want to finish the importing.

I was wondering if it's possible to add an option to continue importing while skipping all the articles already in the database, maybe just query mongodb for that entry's title and jump if it already exists?

I have zero knowledge of node.js, and I would really appreciate it if someone could add it. Thanks!

**Comment by spencermountain** [comment]
yeah, i think if you change `insert` to `upsert` on line 31, it will avoid redundant writes.
the same thing happened to me. it sounds like the problem is bigger. it must being something about the readstream not being garbage collected, or something. it shouldn't get slow like that.
will look when i have some time. maybe later in the week.

**Comment by imoonkey** [comment]
I just realized one thing. Due to the image parsing error, I have restarted the importing program a few times. It turned out that I have 4 records of the same documents for some wikipedia article... Will 'upsert' avoid this problem, as we are not specifying the unique key?

PS. The following is probably off topic, but I tried to query the article in mongodb with a title, and it took more than a minute. There are only about 7,000,000 documents there, is there anything I should do to vastly accelerate this process?

**Comment by spencermountain** [comment]
hey, yeah. you can turn on indexing for the title property. that's in the mongo docs.
also you can set title as a unique field.

**Comment by imoonkey** [comment]
Great. The indexing helped a lot.

**Comment by spencermountain** [comment]
cause of this idea, am using encoded title as `_id` field. you can re-run it, and it won't double your articles.
there may be a 'non-unique id' warning, but you can ignore it.
cheers
