### ISSUE TITLE
TypeError with worker.js

### ISSUE THREAD

**Issue by MTKnife** [spencermountain/wikipedia-to-mongodb#20]
I seem to have wp2mongo running just fine (under Windows 10) with a bz dump I had already downloaded.  However, when I try to do things with Redis, I run into a problem.  A script called by worker.js is throwing the following error, apparently on every article (none of them get into the db):

> 
> C:\code\JavaScript\wikipedia-to-mongodb\node_modules\wtf_wikipedia\src\parse\infobox\index.js:32
>         let inside = tmpl.match(/^\{\{nowrap\|(.*?)\}\}$/)[1];
>                                                           ^
> 
> TypeError: Cannot read property '1' of null
>     at C:\code\JavaScript\wikipedia-to-mongodb\node_modules\wtf_wikipedia\src\parse\infobox\index.js:3
>     at Array.forEach (<anonymous>)
>     at Object.parse_recursive [as infobox] (C:\code\JavaScript\wikipedia-to-mongodb\node_modules\wtf_w
> \infobox\index.js:19:11)
>     at main (C:\code\JavaScript\wikipedia-to-mongodb\node_modules\wtf_wikipedia\src\parse\index.js:46:
>     at Object.parse (C:\code\JavaScript\wikipedia-to-mongodb\node_modules\wtf_wikipedia\src\index.js:4
>     at Object.parse (C:\code\JavaScript\wikipedia-to-mongodb\src\doPage.js:50:18)
>     at C:\code\JavaScript\wikipedia-to-mongodb\src\worker.js:25:14
>     at Worker.<anonymous> (C:\code\JavaScript\wikipedia-to-mongodb\node_modules\kue\lib\queue\worker.j
>     at Job.<anonymous> (C:\code\JavaScript\wikipedia-to-mongodb\node_modules\kue\lib\queue\job.js:706:
>     at multi_callback (C:\code\JavaScript\wikipedia-to-mongodb\node_modules\redis\lib\multi.js:89:14)

(The caret in the third line should point to the "[1]".)

Evidently this sort of error with regexes is not uncommon, but I can't figure out why I'm getting it here.

EDIT:  I _thought_ wp2mongo was working fine, but it's reliably hanging on article number 777.  After it took literally _days_ to get the app compiled (apparently due to a corrupt file, following by the thing looking for a dependency in the wrong place), I'm starting to think this is the hardest "easy way" I've ever experienced.

**Comment by spencermountain** [comment]
hey thanks Scott, i'm gonna merge this with #21
