### ISSUE TITLE
Suggested option to omit redirects and disambiguation pages

### ISSUE THREAD

**Issue by MTKnife** [spencermountain/wikipedia-to-mongodb#22]
Issue  #19 concerned the number of articles in the English _Wikipedia_, and it was noted that a large proportion of them are redirects.  I'd like to add a little extra insight, and make a suggestion.

As I mentioned in issue #21 , during the first 16 hours of the run (on my reasonably beefy PC portable workstation), the app got through nearly 7.4 million articles.  In the two days since then, it's gotten through a bit over 2.3 million.  In other words, the progress  through the dump is not linear.

I assume the later articles don't require dramatically more parsing time than the earlier ones.  Moreover, the Node.js and Mongo DB processes together are using over 3GB of RAM, but they're not taxing the machine (I can still use it normally for everything else I have to do).  My conclusion, therefore, is that the big slowdown is coming from the increasing difficulty of inserting new records as the size of the collection and its indices grows.

Therefore, I suggest adding an option to skip redirects (and probably disambiguation pages as well):  for some purposes, including mine, these aren't needed, and not having to index them would _dramatically_ cut the run time.

**Comment by spencermountain** [comment]
hey Scott, yeah good idea, lets try it out.
this [is ready](https://github.com/spencermountain/wikipedia-to-mongodb#skip-unnecessary-pages---skip_disambig---skip_redirects) in `2.3.0` 
lemme know if it helps.

**Comment by spencermountain** [comment]
this is the default behaviour now, thanks for the help!
