### ISSUE TITLE
parse dump file "page-meta-history"

### ISSUE THREAD

**Issue by cafeine05** [spencermountain/wikipedia-to-mongodb#4]
Hi,

Thank you for your amazing work. I was wondering if your script could be used to put into a mongoDB collection the dump called "page-meta-history" which is much more complete than the "pages-articles" you are refering to.

**Comment by spencermountain** [comment]
hi Léo, thanks. ah, yeah. that's a good question.
i haven't looked at the format of the page-meta-history dump, but if it's xml, [xml-stream](https://github.com/assistunion/xml-stream) will be able to pluck anything you'd like from it. 
i reckon [this line](https://github.com/spencermountain/wikipedia-to-mongodb/blob/master/index.js#L27) would need to change to the new format.
would be a great pull request, if you figure it out. I'm happy to help
cheers

**Comment by cafeine05** [comment]
I found a way for the very little wiki, with not a big dump. I will soon make a pull request to show you. But I need now (for phD in sociology purpose ;) ) to make the script wor in the french wiki, with very very very very large dumps file (like lots of TB)

As I definetely can't unzip those files, I was wondering if you now a way to stream the file with sml-stream WITHOUT unzip the file.

thank you

**Comment by spencermountain** [comment]
sounds good Léo. not sure. good luck!

**Comment by spencermountain** [comment]
are you friends with Matheus?
https://github.com/spencermountain/wikipedia-to-mongodb/pull/6

**Comment by mcassiano** [comment]
@spencermountain nope!

**Comment by spencermountain** [comment]
you are now ;) check it out, it's no longer necessary to unzip beforehand. should help you a lot

**Comment by mcassiano** [comment]
@spencermountain @cafeine05 fair enough hahaha
