### ISSUE TITLE
A mongod problem importing afrikaans Wikipedia

### ISSUE THREAD

**Issue by cafeine05** [spencermountain/wikipedia-to-mongodb#5]
Hi,

I have a problem importing the example wiki you gave. When Iaunch the command "node index.js af-wiki..." I get after some time the following message :
 
```
{ [MongoError: server localhost:27017 sockets closed]
  name: 'MongoError',
  message: 'server localhost:27017 sockets closed' }
```

And also my mongo shell show e 9 simultaneous connections. Is that normal ?

Thank you

**Comment by spencermountain** [comment]
hey leo, yeah, it will run as fast as xml-stream can read, which means there may be many connections.
dunno about that, as far as i know, sockets shouldn't close until `db.close()`.

**Comment by cafeine05** [comment]
Solved ! It was only necessery to wait a little more than 3000 ms at the end ! I would soon make a pull request integrating the other issue I made.
