### ISSUE TITLE
Jade to Pug

### ISSUE THREAD

**Issue by hash-include** [spencermountain/wikipedia-to-mongodb#9]
Hi

I am exploring this repo as part of wikipedia data analysis. 

check if this is useful for you:
08:59 $ npm install -g wikipedia-to-mongodb/
npm WARN deprecated jade@1.11.0: Jade has been renamed to pug, please install the latest version of pug instead of jade

I think some documentation would go a long way to make this repo awesome :) Let me know if I can help. I don't know JS, I'm java guy for all I know.

Sri Harsha

**Comment by spencermountain** [comment]
;) hi Sri! thanks. I'll check out the dependency thing.
i'm a little swamped today, but would love some help, I agree it's not very clear. Let me kick this forward a bit tonight, then I'll pass it to you 😎 
cheers!

**Comment by spencermountain** [comment]
hey Sri, thanks. I've moved some things around. The old-dependency-warning is from another package, so there's nothing we can do about it I think. Welcome to javascript-land!

i've done some updates to the docs, but should do more. let me know what you run into!
cheers
